In [2]:
import pandas as pd
df = pd.read_csv("https://github.com/MarcusHutch/MHRepository_Public/raw/main/PatientSample.csv")
display(df)

,Number,First_Name,Last_Name,Company_Name,Address,City,County,Postcode,Email,DOB,Gender,LastUpdated
0,10123456,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,atomkiewicz@hotmail.com,15/04/1987,M,08/11/2023 08:55
1,10123457,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,evan.zigomalas@gmail.com,03/12/1975,F,08/11/2023 08:55
2,10123458,France,Andrade,Elliott John W Esq,8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,france.andrade@hotmail.com,22/09/1999,F,08/11/2023 08:55
3,10123459,Ulysses,Mcwalters,Mcmahan Ben L,505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,ulysses@hotmail.com,09/05/1968,F,08/11/2023 08:55
4,10123460,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,tyisha.veness@hotmail.com,31/10/2005,M,08/11/2023 08:55
5,10123461,Eric,Rampy,Thompson Michael C Esq,9472 Lind St,Desborough,Northamptonshire,NN14 2GH,erampy@rampy.co.uk,18/07/1990,M,08/11/2023 08:55
6,10123462,Marg,Grasmick,Wrangle Hill Auto Auct & Slvg,7457 Cowl St #70,Bargate Ward,Southampton,SO14 3TY,marg@hotmail.com,26/02/1983,M,08/11/2023 08:55
7,10123463,Laquita,Hisaw,In Communications Inc,20 Gloucester Pl #96,Chirton Ward,Tyne & Wear,NE29 7AD,laquita@yahoo.com,07/11/1976,M,08/11/2023 08:55
8,10123464,Lura,Manzella,Bizerba Usa Inc,929 Augustine St,Staple Hill Ward,South Gloucestershire,BS16 4LL,lura@hotmail.com,11/08/1955,M,08/11/2023 08:55
9,10123505,Test,Testing,Test Company,Test Street,Test Ward,Testshire,TE5 5TT,test@yahoo.com,31/03/1962,U,16/11/2023 14:25
10,10123507,Test1,Testing1,Test Company1,Test Street1,Test Ward1,Testshire1,TE51 5TT,test1@yahoo.com,31/01/1911,U,16/11/2023 16:03